version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "kwitsch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "kwitsch"
