linters:
  presets:
    - bugs
    - unused

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - dupl
        - gosec

run:
  skip-files:
    - tools.go
